### ISSUE TITLE
Add inbounds

### ISSUE THREAD

**Issue by TorkelE** [JuliaDiffEq/DiffEqBiological.jl#100]
Just closed the dormant PR we have had on this one for a while (https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/38). Don't fully remember why it was skipped, but there were some issue with it. Opened an issue on the topic until we revisit it.

**Comment by isaacsas** [comment]
This should now be handled by [#101](https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/101) for the ODE rhs and related Jacobians. I think SDE noise terms and Jump related functions still need this.

**Comment by ChrisRackauckas** [comment]
The SDE function uses the same path I think. The jumps need something different.

**Comment by isaacsas** [comment]
Closed by [103](https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/103).
