### ISSUE TITLE
get rid of Any's in reaction_network.jl

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqBiological.jl#104]
I think almost all the remaining `Any`s should be replaceable by `Union{Expr,Symbol,Number}`.

**Comment by ChrisRackauckas** [comment]
`ExprValues` IMO is a bit more explicit.

**Comment by isaacsas** [comment]
I agree, we should add a type name for the `Union`.

**Comment by TorkelE** [comment]
I am almost surprised that such a type don't exist already, since it appears so naturally. Yes lets add a type. If non one have done it by tomorrow afternoon I will fix it then.

**Comment by isaacsas** [comment]
Closed by [106](
https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/106)
