### ISSUE TITLE
Enable Two Way Reactions

### ISSUE THREAD

**Issue by Gaussia** [JuliaDiffEq/DiffEqBiological.jl#11]
If you have a simple reaction System X <--> Y then it requires you to write
k1, X --> Y
k2, Y --> X
if there were some way to rather write
(k1,k2), X<-->Y
that would save a lot of space (especially for models were most reactions goes in both directions). In this case it seems like you cannot use the arrow "<-->" in expressions. However the possibility of reducing these reactions to a single line would be very useful.

**Comment by ChrisRackauckas** [comment]
Sounds like a great idea. I am not sure I'll get to it soon though.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/15
