### ISSUE TITLE
warnings for `solve`

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqBiological.jl#138]
`WARNING: both HomotopyContinuation and DiffEqJump export "solve"; uses of it in module DiffEqBiological must be qualified`

**Comment by TorkelE** [comment]
@ChrisRackauckas Exactly how should `import HomotopyContinuation` be used to remedy this? I tried simply replacing `using HomotopyContinuation` with `import HomotopyContinuation` in the `DiffEqBiological.jl` file, but this gives error when running tests (first tests were homotopycontinuation was used).

**Comment by ChrisRackauckas** [comment]
you shouldn't export `HomotopyContinuation.solve`.

**Comment by ChrisRackauckas** [comment]
I'll try to make a `CommonSolve.jl` today.
