### ISSUE TITLE
bifurcation_grid_2d and bifurcation_grid_diagram does not seem to work. 

### ISSUE THREAD

**Issue by danielchen26** [JuliaDiffEq/DiffEqBiological.jl#145]
Following the example below
`rn = @reaction_network begin
  (p,d), 0 ↔ X
end p d
params = [1.,2.] #The value of 'p' here doesn't really matter, however, the field must exist.
bif = bifurcations(rn, params, :d, (0.1,5.))
​
# below does not work
bif_grid_2d = bifurcation_grid_2d(rn, params, :p, 1.:5. :d, 2.:10.) 
bif_grid_dia = bifurcation_grid_diagram(rn, params, :p, 1.:5. :d, (2.,10.))
plot(bif)`

bifurcation_grid_2d and bifurcation_grid_diagram does not seem to work. The error says d is not defined.

**Comment by isaacsas** [comment]
@TorkelE

**Comment by TorkelE** [comment]
Seem like the is a missing `,` just before `:d` in the function call in the code. I will update the docs.

**Comment by danielchen26** [comment]
Thanks for update

**Comment by TorkelE** [comment]
Should be updated now.
