### ISSUE TITLE
`stability` does not seems to correct when directly compared with ODE plots

### ISSUE THREAD

**Issue by danielchen26** [JuliaDiffEq/DiffEqBiological.jl#146]
My code:

`# define the random sum func, n:= number of data points, dim:= dimension, tot:= vector sum total.
function randfixsum(n, dim, tot)
    sol = []
    for i in 1: n
        v = rand(1,dim)
        nv = tot*v./sum(v)
        push!(sol, nv)
    end
    return sol
end
#reaction network
rn = @reaction_network begin
  (k1,k2), X ↔ Y
  (k3,k4), V ↔ W
end k1 k2 k3 k4
params = [2.,1.,1.,2.]
@add_constraints rn begin
  X + Y = 2.
  V + W = 4.
end
s = steady_states(rn,params)
stability(s, rn , params)

tspan = (0,1e5)
anim = @animate for u01 in randfixsum(10,2,2) , u02 in randfixsum(10,2,2)
    u0 = [u01 u02]
    oprob = ODEProblem(rn, u0, tspan, params)
    osol  = solve(oprob, Rosenbrock23())
    plot(osol,ylims = (0,2))
    # calculate eig_spectrum
    t = 0.0
    out = rand(4,4)
    rn.jac(out,osol[end],params,t)
    @show eig = eigen(out).values
end
gif(anim, fps = 1)`

final ode plots are stable. `stability` shows `false`.

**Comment by isaacsas** [comment]
@TorkelE

**Comment by TorkelE** [comment]
Can confirm that I can reproduce. My guess is that it is related to `@add_constraints`. I will have to investigate during the week, especially figure out why it is not caught in the tests.

**Comment by danielchen26** [comment]
Thanks for update. Let me know when it is fixed

**Comment by isaacsas** [comment]
@TorkelE this should be fixed on master now, right?

**Comment by TorkelE** [comment]
Yes
