### ISSUE TITLE
Parallelise tests

### ISSUE THREAD

**Issue by TorkelE** [JuliaDiffEq/DiffEqBiological.jl#157]
@isaacsas Said that this was possible, with an example? I've think I remember it, but have forgotten when and where...

If it could reduce the test run time it could be convenient, not sure if there are any drawbacks.

**Comment by isaacsas** [comment]
I think the Travis file for OrdinaryDiffEq.jl uses groups to achieve this. It would also require some tweaks to the runtests file. Not sure if it can be done on Appveyor, which is the real issue.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/181
