### ISSUE TITLE
Unsatisfiable requirements - HomotopyContinuation

### ISSUE THREAD

**Issue by korsbo** [JuliaDiffEq/DiffEqBiological.jl#177]
The CI tests currently fail with an unsatisfiable version restriction on HomotopyContinuation. 

Failing HomotopyContinuation:
https://travis-ci.org/JuliaDiffEq/DiffEqBiological.jl/jobs/618522172

It seems that we are restricting ourselves to HomotopyContinuation v0.7 when the newest version is v1.2.1. This old version of HomotopyContinuation is not specified as compatible with the newer versions of DynamicPolynomials that we have as an explicit requirement.

**Comment by korsbo** [comment]
Related: #174

**Comment by ChrisRackauckas** [comment]
Yeah, getting this package to continue to work is difficult since it requires a really old version of HomotopyContinuations which bounds a bunch of stuff into the past. But it's required because of the changes in the later versions. We need to get that fixed ASAP.

**Comment by korsbo** [comment]
Are we incompatible with later versions of HomotopyContinuation? The errors that I see are all just about irreconcilable compats.

**Comment by korsbo** [comment]
Ping @TorkelE

**Comment by ChrisRackauckas** [comment]
Fixed
