### ISSUE TITLE
HomotopyContinuation bound

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBiological.jl#183]
The HomotopyContinuation bound is highly breaking because it sets StaticArrays to <=0.10. @TorkelE  we need a fix ASAP. Until then, DiffEqBio needs to be removed from the DiffEqProblemLibrary tests and this repo is incompatible with pretty much the rest of the Julia ecosystem.

**Comment by ChrisRackauckas** [comment]
Nevermind, looks like I was just pulling an old version!

**Comment by TorkelE** [comment]
There should be a smiley for "general relief"
