### ISSUE TITLE
Allow turning off save_positions in the reaction network DSL

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBiological.jl#28]
https://github.com/JuliaDiffEq/DiffEqBiological.jl/blob/master/src/reaction_network.jl#L310

That needs to take a `save_positions` argument. @gaussia have you been playing with doing this? I know you asked on the Discourse so I assumed you might have this modified already locally?

@isaacsas

**Comment by Gaussia** [comment]
Right now there is no local changes at all (hope to get started on implementing some changes soon, whenever that is). Did not know that save_positions was needed here. I am quire certain that the Gillespie simulations are not working properly. Been meaning to try and read up on them and have a second look at this part. I am quite sure that ConstantRateJumps shouldn't be used all the time either (e.g. when the rate is time dependent?).

How should the save_positions be included? I can find no mention of them in the documents (for Gillespie Simulations)?

**Comment by ChrisRackauckas** [comment]
>I am quite sure that ConstantRateJumps shouldn't be used all the time either (e.g. when the rate is time dependent?).

Yes, that is true. The traditional method is incorrect when rates change between jump times which is why it's usually just not allowed. For our setup, it's fine if you use a `VariableRateJump`.

>I am quire certain that the Gillespie simulations are not working properly.

What do you mean?

>How should the save_positions be included? I can find no mention of them in the documents (for Gillespie Simulations)?

http://docs.juliadiffeq.org/latest/types/jump_types.html#Defining-a-Constant-Rate-Jump-1

It's a keyword argument in the jump.

**Comment by Gaussia** [comment]
Cheers, that is good. Looked at the Gillespie main page.

So I think the time were I tried the Gillespie Simulations I was using some t dependent rates which caused be thinking (correctly) things were messed up. I haven't actually used it much since (working with SDEs). When I take myself the time to work on the DSL again I will fix the small issues and then check that things looks fine. I will also look at adding the things requested by @isaacsas.

**Comment by ChrisRackauckas** [comment]
Looks like I had this documented slightly wrong. It just needs to be passed to the `JumpProblem` constructor, in which case https://github.com/JuliaDiffEq/DiffEqBiological.jl/commit/06139ecdbc41cffc79b1b5a69d27a43fd310b3f3 was all that was necessary to do this.

**Comment by erlebach** [comment]
Consider: 
```
    dprob = DiscreteProblem(js, initial_state, tspan, initial_params)
    JumpProblem(js, dprob, NRM(); save_positions=(false, false))
    # Save solution at times 0., 0.25, 0.50, etc
    sol = solve(jprob, SSAStepper(), saveat=0.25)
```
"The solution is saved in sol.t every 0.25 time units. However, it is also saved at all the other jump points. It is as if the save_positions argument had no effect. I also tried with the semi-colon replaced by a comma in the argument list to JumpProblem. 

I also posted this message on discourse.julialang.org.
