### ISSUE TITLE
large network parsing speed and memory use

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqBiological.jl#68]
I'm trying to translate a large network (~25,000 reactions) from a simple text file into DiffEqBiological. Right now this seems to be too much to handle. For reference, parsing the network, which is in a simple file with lines of the form:

A + B -> C, 1.0

is super quick. I then translate each line to the appropriate form for use in the `@reaction_network` macro, and construct a full instance of the `@reaction_network` macro as a string. Then I call `eval( Meta.parse(rnstr) )` on this string. The latter seems to take a very large amount of time, and use up a lot of memory. (Up to 17 minutes and 11GB at the moment.) 

Does anyone have a suggestion for a better way to do this?

**Comment by korsbo** [comment]
I write with no certainty what so ever but for issues like this I'm always suspicious of things which do not scale well. The calculation of the Jacobian is one thing which is likely to scale pretty poorly. You could try to comment out the [jacobian calculation](https://github.com/JuliaDiffEq/DiffEqBiological.jl/blob/716f922ea3f6c5040f5d8e9936bc8a7d0c7e438a/src/reaction_network.jl#L96). It also seems to me that this calculation currently does not do anything at all.

**Comment by TorkelE** [comment]
Just double checking, you basically create a string like
```julia
rnstr = "@reaction_network begin
    1.0, A + B --> C
end"
my_network = eval( Meta.parse(rnstr) )
```
?

If you are able to modify the code easily I would put an @time in front of several of the functions in the `coordinate` function in the main file, to try and trace what is causing the time. If something does not scale well it would be good to know what. If it is the jacobian it would maybe be possible to have an option to not calculate it.

**Comment by ChrisRackauckas** [comment]
Yeah, I'm not sure the symbolic calculations will scale well. That's one of the reasons why ModelingToolkit is "query for what you want" instead of building them right into the DSLs. There are probably a few other factors, but simply the scaling on that method is probably the biggest.

**Comment by isaacsas** [comment]
Thanks all for the suggestions. My plan, hopefully next weekend once I'm done grading, is to try commenting out all the code that is generating functions and see what improvement that gives. At least for a mass action (jump) system, I don't think any of the `coordinate` code is really needed after `parameters` gets created. I'll also try to do some profiling on a smaller system to see where the most expense is coming from -- it certainly sounds like the Jacobian part might be a big contributor. (That said, when I killed the B-cell pathway import at the 20 minute mark it was in `get_jumps`, so I don't think it had made it to the `symjac` calculation yet.)

@TorkelE that's exactly what I'm doing.

**Comment by isaacsas** [comment]
Just an update. Commenting out basically everything in `coordinate` within `reaction_network.jl` after `update_reaction_info` until `maketype`, and updating `maketype` to only take `name`, `syms`, `params` and `reactions` lets me import a full B Cell signaling pathway with ~30,000 reactions near instantly. This suggests that splitting apart the ODE/SDE/jump function creation from the reaction network data structure that is initially constructed could really help for large networks. 

It seems like this might then be a good place to discuss a restructuring that makes the creation of these functions optional, or delays them until they are actually needed (i.e. the first time an ODE or jump problem is created).

Any thoughts?

**Comment by TorkelE** [comment]
Have we tried to track down whenever there is a specific part of coordinate which takes a lot more time than there others (if it is only one large network perhaps a set of @time macros would do it)? Might be that it is only specific parts that is the problem.

At some point we need some functionality to accept more options into the macro to allow for things like this, still don't know a pretty way to do it.

My presumption is that we, at some point, will want to integrate it into modelling toolkit. I am not really keeping up to date with the toolkit, but am of the impression that there is still lots of stuff going on with it and that if we are in no hurry we might as well wait a little bit longer for the toolkit to reach full(ish) functionality.

**Comment by isaacsas** [comment]
Ok, here is some preliminary timing on several different networks using `TimerOutputs`. The networks are taken from the collection of models by Thanh et al: [here](https://www.cosbi.eu/prototypes/jLiexDeBIgFV4zxwnKiW97oc4BjTtIoRGajqdUz4.zip). There is no license on these models, so I haven't posted them online... It might make sense for me to email the authors and see if they would let me put them into DiffEqBenchmarks under an MIT license. In any case some results (here the "Section" numbers refer to the line number within `coordinate`).

5 Species "Gene expression" model:

<pre>
──────────────────────────────────────────────────────────────────
                           Time                   Allocations      
                   ──────────────────────   ───────────────────────
 Tot / % measured:       225s / 0.89%           12.2GiB / 3.23%    

 Section   ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────
 1              3    1.03s  51.1%   342ms    314MiB  77.9%   105MiB
 8              3    273ms  13.6%  91.1ms   34.6MiB  8.58%  11.5MiB
 7              3    228ms  11.3%  76.1ms   11.9MiB  2.95%  3.96MiB
 19             2    101ms  5.02%  50.5ms   8.08MiB  2.00%  4.04MiB
 13             3    100ms  4.96%  33.2ms   5.38MiB  1.33%  1.79MiB
 16             2   84.0ms  4.18%  42.0ms   13.8MiB  3.42%  6.88MiB
 15             2   53.3ms  2.65%  26.7ms   1.69MiB  0.42%   865KiB
 14             3   48.5ms  2.41%  16.2ms   3.11MiB  0.77%  1.04MiB
 18             2   39.0ms  1.94%  19.5ms   3.02MiB  0.75%  1.51MiB
 9              3   18.3ms  0.91%  6.10ms    855KiB  0.21%   285KiB
 20             2   17.9ms  0.89%  8.95ms   2.73MiB  0.68%  1.37MiB
 10             3   13.2ms  0.66%  4.40ms   3.65MiB  0.91%  1.22MiB
 2              3   6.72ms  0.33%  2.24ms   88.6KiB  0.02%  29.5KiB
 11             3    308μs  0.02%   103μs   94.8KiB  0.02%  31.6KiB
 6              3   98.6μs  0.00%  32.9μs   83.5KiB  0.02%  27.8KiB
 3              3   10.6μs  0.00%  3.53μs   1.03KiB  0.00%        -
 4              3   8.25μs  0.00%  2.75μs   9.23KiB  0.00%  3.08KiB
 12             3   6.39μs  0.00%  2.13μs   1.13KiB  0.00%        -
 25             2   4.90μs  0.00%  2.45μs   2.41KiB  0.00%  1.20KiB
 23             2   4.42μs  0.00%  2.21μs   2.13KiB  0.00%  1.06KiB
 17             2   4.15μs  0.00%  2.08μs         -  0.00%        -
 5              3   3.27μs  0.00%  1.09μs         -  0.00%        -
 22             2   2.98μs  0.00%  1.49μs         -  0.00%        -
 29             2   1.92μs  0.00%   960ns         -  0.00%        -
 21             2   1.73μs  0.00%   864ns         -  0.00%        -
 27             2    654ns  0.00%   327ns         -  0.00%        -
 28             2    588ns  0.00%   294ns         -  0.00%        -
 24             2    475ns  0.00%   238ns         -  0.00%        -
 26             2    367ns  0.00%   184ns         -  0.00%        -
 ──────────────────────────────────────────────────────────────────
</pre>

296 Reaction MAPK Model:
<pre>
 ──────────────────────────────────────────────────────────────────
                           Time                   Allocations      
                   ──────────────────────   ───────────────────────
 Tot / % measured:       443s / 0.73%           12.4GiB / 4.39%    

 Section   ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────
 1              4    1.12s  34.6%   280ms    322MiB  57.7%  80.6MiB
 15             3    788ms  24.4%   263ms   79.1MiB  14.2%  26.4MiB
 8              4    294ms  9.09%  73.5ms   37.7MiB  6.74%  9.42MiB
 7              4    229ms  7.07%  57.1ms   12.0MiB  2.14%  3.00MiB
 10             4    201ms  6.22%  50.3ms   48.5MiB  8.67%  12.1MiB
 11             4    128ms  3.95%  31.9ms   16.2MiB  2.90%  4.05MiB
 19             3    128ms  3.95%  42.5ms   9.61MiB  1.72%  3.20MiB
 13             4    123ms  3.80%  30.7ms   8.82MiB  1.58%  2.21MiB
 16             3   90.5ms  2.80%  30.2ms   14.2MiB  2.54%  4.74MiB
 14             4   48.5ms  1.50%  12.1ms   3.11MiB  0.56%   796KiB
 18             3   39.0ms  1.21%  13.0ms   3.02MiB  0.54%  1.01MiB
 9              4   19.7ms  0.61%  4.92ms   1.19MiB  0.21%   306KiB
 20             3   17.9ms  0.55%  5.97ms   2.74MiB  0.49%   935KiB
 2              4   6.78ms  0.21%  1.70ms   95.0KiB  0.02%  23.8KiB
 12             4    124μs  0.00%  31.0μs    237KiB  0.04%  59.3KiB
 6              4    109μs  0.00%  27.4μs   89.8KiB  0.02%  22.4KiB
 3              4   11.2μs  0.00%  2.81μs   1.38KiB  0.00%        -
 4              4   9.22μs  0.00%  2.30μs   10.1KiB  0.00%  2.53KiB
 23             3   6.53μs  0.00%  2.18μs   3.19KiB  0.00%  1.06KiB
 25             3   6.06μs  0.00%  2.02μs   3.61KiB  0.00%  1.20KiB
 17             3   4.89μs  0.00%  1.63μs         -  0.00%        -
 5              4   3.59μs  0.00%   898ns         -  0.00%        -
 22             3   3.12μs  0.00%  1.04μs         -  0.00%        -
 29             3   2.82μs  0.00%   940ns         -  0.00%        -
 21             3   2.57μs  0.00%   857ns         -  0.00%        -
 27             3    875ns  0.00%   292ns         -  0.00%        -
 28             3    795ns  0.00%   265ns         -  0.00%        -
 24             3    609ns  0.00%   203ns         -  0.00%        -
 26             3    556ns  0.00%   185ns         -  0.00%        -
 ──────────────────────────────────────────────────────────────────
</pre>

3862 reaction FceRI network:
<pre>
 ──────────────────────────────────────────────────────────────────
                           Time                   Allocations      
                   ──────────────────────   ───────────────────────
 Tot / % measured:       643s / 8.39%           19.3GiB / 36.5%    

 Section   ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────
 11             5    23.4s  43.4%   4.68s    793MiB  11.0%   159MiB
 10             5    15.3s  28.4%   3.06s   2.21GiB  31.3%   452MiB
 15             4    12.6s  23.3%   3.15s   3.52GiB  50.0%   902MiB
 1              5    1.16s  2.14%   232ms    364MiB  5.05%  72.8MiB
 8              5    414ms  0.77%  82.8ms   51.6MiB  0.72%  10.3MiB
 13             5    313ms  0.58%  62.5ms   47.0MiB  0.65%  9.39MiB
 7              5    239ms  0.44%  47.9ms   13.4MiB  0.19%  2.69MiB
 16             4    231ms  0.43%  57.8ms   20.5MiB  0.28%  5.12MiB
 19             4    166ms  0.31%  41.5ms   32.0MiB  0.44%  8.00MiB
 14             5   48.5ms  0.09%  9.70ms   3.11MiB  0.04%   637KiB
 18             4   39.1ms  0.07%  9.77ms   3.03MiB  0.04%   775KiB
 9              5   38.5ms  0.07%  7.69ms   6.21MiB  0.09%  1.24MiB
 20             4   17.9ms  0.03%  4.48ms   2.75MiB  0.04%   703KiB
 2              5   7.58ms  0.01%  1.52ms    118KiB  0.00%  23.6KiB
 12             5   6.16ms  0.01%  1.23ms   11.4MiB  0.16%  2.29MiB
 6              5    138μs  0.00%  27.7μs    111KiB  0.00%  22.3KiB
 3              5   12.2μs  0.00%  2.45μs   1.72KiB  0.00%        -
 4              5   11.0μs  0.00%  2.21μs   13.3KiB  0.00%  2.65KiB
 23             4   9.06μs  0.00%  2.26μs   4.25KiB  0.00%  1.06KiB
 25             4   8.05μs  0.00%  2.01μs   4.81KiB  0.00%  1.20KiB
 17             4   5.59μs  0.00%  1.40μs         -  0.00%        -
 29             4   4.19μs  0.00%  1.05μs   1.06KiB  0.00%        -
 5              5   4.04μs  0.00%   808ns         -  0.00%        -
 21             4   3.56μs  0.00%   891ns         -  0.00%        -
 22             4   3.27μs  0.00%   819ns         -  0.00%        -
 27             4   1.19μs  0.00%   299ns   1.00KiB  0.00%        -
 28             4   1.13μs  0.00%   283ns         -  0.00%        -
 24             4    792ns  0.00%   198ns         -  0.00%        -
 26             4    738ns  0.00%   185ns         -  0.00%        -
 ──────────────────────────────────────────────────────────────────
</pre>


I haven't tried the full B cell model (which is > 20,000 reactions) without turning off the function generation -- it was just too slow last time I looked at it. 

From the above timings it appears that for small networks the call to `get_reactions` is rate limiting. For the largest network making `g`, `g_expr`, and `symjac` are the dominant costs (with significant memory allocations too). I guess next I'll see if turning off those three are sufficient to get the B cell model loaded in a reasonable amount of time.

**Comment by ChrisRackauckas** [comment]
>It seems like this might then be a good place to discuss a restructuring that makes the creation of these functions optional, or delays them until they are actually needed (i.e. the first time an ODE or jump problem is created).

I think "query for what you want" is probably the right approach. Building the Jacobian symbolically is good but not always what people want, especially when this is not always used for ODEs/SDEs.

**Comment by isaacsas** [comment]
> I think "query for what you want" is probably the right approach. Building the Jacobian symbolically is good but not always what people want, especially when this is not always used for ODEs/SDEs.

So is it reasonable to consider changes that break the current interface? We could return a much more minimal reaction network from the macro, and then provide helper methods users could call to generate Jacobians and such. Modifying the appropriate `Problem` definitions would allow Jacobians, jump functions, etc to be constructed automatically from the more minimal `reaction_network` if needed, while also allowing a user who has previously constructed them to simply pass them in as kwargs. This would also allow users to potentially turn off symbolic Jacobians for ODE problems if desired.

If this approach sounds reasonable I could take a first pass at it, though I'm not sure what the timescale on getting it done would be.

**Comment by ChrisRackauckas** [comment]
I think it's not just reasonable but also needs to be done. Jacobian calculations scale like O(n^2) with a high constant cost, while lots of other things are just O(n). The g calculation is O(n^2) as well since it's building a noise matrix. Those two just have worse scaling than the other parts and so even if optimized they will be the issue for larger networks. So even though we are working on a full Terms.jl+Rewrite.jl+ModelingToolkit.jl symbolic system that should make this size possible, it will always be the case that those computations will be much much slower for any large network and so I think it needs to be optional.

**Comment by isaacsas** [comment]
@korsbo @TorkelE 
Do either of you know if the symbolic Jacobian is actually ever used. Similarly, is the out of place ODE rhs functor ever used? If not, why define it? (More generally, the way the latter is defined doesn't seem particularly useful -- for example, we can't use StaticArrays with this type of out-of-place definition, right?)

I ask as in working on a query-based interface I'm trying to understand whether we need to really generate either of these when constructing ODE/SDE/Jump problems. My understanding is that right now an `AbstractReactionNetwork` based ODE/SDE problem uses only the in-place rhs, and does not use the symbolic Jacobian we currently calculate.

**Comment by isaacsas** [comment]
Just to clarify, do you mean that only the in place RHS is currently used when building an `ODEProblem` or `SDEProblem` from a reaction network?

Is there anywhere that documents what fields within a structure passed into an `ODEProblem` or `SDEProblem` would be used? Right now the reaction network has lots of fields, and it would be helpful in setting up a query-based approach to understand which ones are actually used in building different problem types. (I understand that functors are defined for both the in-place and out-of-place ODE RHS.) Is just having the `symjac` field as currently defined all that is needed for `ODEProblem`s to then build the Jacobian?

**Comment by ChrisRackauckas** [comment]
>Is there anywhere that documents what fields within a structure passed into an ODEProblem or SDEProblem would be used? 

http://docs.juliadiffeq.org/latest/features/performance_overloads.html

>do you mean that only the in place RHS is currently used when building an ODEProblem or SDEProblem from a reaction network?

It's not used anywhere unless the user specifically tells it. The ODEProblem and SDEProblem use the in-place functions that are built unless one uses `ODEProblem{false}(...)` which is probably very very rare (but useful if one wanted to use static arrays).

The Jacobian function is built using the symjac before the ODEProblem call. It's a function just like `f` that's just passed along to the solver. It doesn't really need to be a field for the solvers, though it is calculated along the way in order to build said functions for the solvers, and it's then stored for usage in output controls like Latexify.jl.

**Comment by isaacsas** [comment]
Thanks for the link! It seems like we might want to then have the workflow be to build a reduced `reaction_network` representation, then the first time one calls `ODEProblem` build and cache an `ODEFunction` from this reduced representation (and similar for SDEs). 

At least for now, when I run the following with DiffEqBiological master I get no Jacobian in the `ODEFunction` that is created:
```
using DifferentialEquations
sir_model = @reaction_network SIR begin
  c1, s + i --> 2i
  c2, i --> r
end c1 c2
p = (0.1/1000,0.01)
u0 = [999.,1.,0.]
tspan = (0.,250.)
prob = ODEProblem(sir_model,u0,tspan,p)
```
i.e. `prob.f.jac` is `nothing`. This looks to me like there is no communication of a Jacobian from the `reaction_network` into an `ODEProblem` currently, but perhaps I'm still misunderstanding. (In which case could you let me know at which step an analytic Jacobian evaluation function is being built from the expressions in `sir_model.symjac`?)

**Comment by korsbo** [comment]
I don't think that the jacobian is used at all at the moment. The idea was to supply it to `ODEProblem` (and I still think that this would be a good idea), but I don't think that ever happened.

**Comment by TorkelE** [comment]
Been away a bit, but back in office now. To my knowledge the Jacobian is not used for `ODEProblem`s, but maybe at some point. I have a package https://github.com/TorkelE/BRNEquilibrate for doing stability analysis which do uses the Jacobian to determine stability.

However, it would maybe make sense to make a `gen_jac` function, and then the functions that need them calculates it (whenever it is for stability analysis or better solving).

If you get to reactants in the thousands the Jacobian gets really large (and the noise functions). However, these should both be quite sparse. Would it be possible to get around some of the problems by making these sparse matrices? 
(Not suggestion that we do it, but if this is at some point needed it would be interesting to know whenever such a modification would be possible)

**Comment by isaacsas** [comment]
I look forward to trying BRNEquilibrate out. Having a good package for making bifurcation plots and such would be awesome. (I teach a class where I perpetually want to have students make bifurcation plots, but haven't yet found a tool I'm comfortable supporting for undergraduates with minimal programming background...)

Thanks for letting me know about the Jacobian calculations, this was my conclusion too.

**Comment by ChrisRackauckas** [comment]
>If you get to reactants in the thousands the Jacobian gets really large (and the noise functions). However, these should both be quite sparse. Would it be possible to get around some of the problems by making these sparse matrices?

Yes, it would probably cut down on the number of calculations if we only fill in where we need to. I think right now we just do the full n^2 loop instead of actually finding out where we have interactions and differentiating that.

**Comment by isaacsas** [comment]
While there is certainly more that can be done for Jacobians, my concerns are pretty much addressed by [74](https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/74), so I'll close this. We can open a separate issue for speeding up specific features if needed.
