### ISSUE TITLE
Support for SteadyStateProblem

### ISSUE THREAD

**Issue by jonstrutz11** [JuliaDiffEq/DiffEqBiological.jl#77]
I noticed DiffEqBiological.jl supports ODEProblem SDEProblem, and JumpProblem. Are there plans to support SteadyStateProblem as well? Often in biological models built using ODEs, people are interested in solving for the steady-state fluxes, concentrations, etc. after applying some perturbation (e.g. an enzyme overexpression).

**Comment by isaacsas** [comment]
It should support steady state problems too. Have you found an example it doesn’t work on?

**Comment by jonstrutz11** [comment]
I have not - I haven't actually used the package yet. I'm currently in the planning phase of my project and just reading a lot of documentation. I noticed that in the documentation for DiffEqBiological.jl, it didn't say that SteadyStateProblem was supported, which is why I opened the issue.

Maybe we should make that more clear in the documentation? Even if that might be obvious for those that are more familiar with the package.

**Comment by isaacsas** [comment]
Yeah, we should definitely update the docs with an example, both the README and in the main DiffEq explanation of the DSL. We need to update them anyways for the new `min_reaction_network` macro, so I'll try to take care of adding a steady-state example when I get that added in.

**Comment by isaacsas** [comment]
OK, README and docs are now updated so I'll close this. If you have any issues when you get to looking at SS problems feel free to file a new issue.
