### ISSUE TITLE
stoichiometric matrix as alternative input

### ISSUE THREAD

**Issue by jonstrutz11** [JuliaDiffEq/DiffEqBiological.jl#78]
DiffEqBiological.jl makes it easy to go from a reaction network (defined using the DSL) to an ODEProblem.

However, large biological models (100s of reactions +) are often encoded in a more convenient format such as SBML. That said, it would be great if we could input a stoichiometric matrix directly instead of listing the reactions in the DSL, as an alternative input. We would also need to input a vector of rates as well.

This would allow those with large biological models to go from a stoichiometric matrix (which can be generated using COBRA tools) directly to an ODEProblem.

**Comment by isaacsas** [comment]
Can COBRA load SBML files? If so it would be great to get a translation layer developed.

**Comment by ChrisRackauckas** [comment]
See the discussion at https://github.com/opencobra/COBRA.jl/issues/13 . Specifically, https://stochasticreveller.wordpress.com/2016/08/02/sbml-and-the-julia-programming-language/ would make a good package. Then it would be up to us to support using it. That would make for a good GSoC project, but I am not sure if I can attract a student to it.

**Comment by isaacsas** [comment]
Getting SBML support would be great, but it poses two big challenges:

1. The SBML API is gigantic, just wrapping the Python libsbml would be a major undertaking.
2. Even having a Julia-based interface to the API, it would be a ton of work to adapt DiffEqBiological to support the many SBML features. We would need support for species tagged to specific compartments (with different volumes(, mixed units, arbitrary mathematical expressions, and lots more. 
That seems like a task for a full-time

**Comment by isaacsas** [comment]
@jonstrutz11 Is your stoichiometric matrix just for fundamental reactions (i.e. no Hill expressions or such)? If so it might be possible to write a converter to import it into a reaction network. 

One thing we should explore is the structure of the ODE and SDE functions we currently generate. Right now I think it is just a single monolithic function, but I wonder if instead calling a mass action reaction evaluation function as we do for jumps might offer better performance for large reaction networks. @ChrisRackauckas any thoughts?

**Comment by isaacsas** [comment]
What about if one has several thousand species and tens of thousands of reactions? Could the ODE rhs function size lead to cache issues? You're probably right that it wouldn't make a difference, but having never coded up a single function that long I don't really know what effect it could have.

Even if one puts all the rate evaluations directly in the generated ODE rhs function, could there be an advantage to not evaluating rate terms multiple times in different ODEs, as currently done, but instead looping through the reactions, evaluating their rate, and adding that contribution into the corresponding `du` entries?

**Comment by jonstrutz11** [comment]
Yes, so I would be loading an SBML model and converting each reaction into a series of elementary reactions (using my own code). At that point, I could use a tool like cobrapy to create a stoichiometric matrix describing all of those elementary reactions, which I need to convert to an ODEProblem (assuming mass action kinetics).

It seems like COBRA.jl cannot take in SBML files, but I know that [cobrapy](https://cobrapy.readthedocs.io/en/latest/io.html) can be used to load SBML files and can also generate a stoichiometric matrix.

**Comment by jonstrutz11** [comment]
Yeah that is right - I didn't think about reactions with the same metabolite on each side. So actually, using an S-matrix wouldn't work as well as I thought. Thanks for catching that!

I originally thought to do the alternative option as you suggest, but thought it might be easier to go from the S-matrix directly, if possible. However, after this discussion, it now seems that just generating a string that encodes the DSL might be the easier way forward.

**Comment by isaacsas** [comment]
If you look at my [ParseRxNetwork](https://github.com/isaacsas/ParseRxNetwork) package you can see how to generate a `reaction_network` from a simple text file of the form:

```
S1 -> S3 , 1.82e-4
S3 -> S2 , 9.1e-5
S2 -> S3 , 1.5e-3
S3 -> S1 , 7.5e-4
S3 + S6 -> S7 , 1.53e-8
S2 + S6 -> S8 , 3.06e-8
S4 + S6 -> S9 , 5e-5
...
```

**Comment by jonstrutz11** [comment]
Great! Thank you!

**Comment by isaacsas** [comment]
I'm closing this as [ReactionNetworkImporters.jl](https://github.com/isaacsas/ReactionNetworkImporters.jl) now supports constructing a `reaction_network` from substrate and product stoichiometric matrcies (dense or sparse).
