### ISSUE TITLE
Broken Jump equations. 

### ISSUE THREAD

**Issue by korsbo** [JuliaDiffEq/DiffEqBiological.jl#83]
After I updated my packages, the jump equations from `@reaction_network`s have acquired a bug. I don't know if it is from here or from DiffEqJump. 

The issue occurs when I use a function for the reaction rates

```julia
using DifferentialEquations
using Plots


model = @reaction_network test1 begin
    (p_x, d_x), 0 ↔ x
    (hill(x, p_y, 1, 1), d_y), 0 ↔ y
    end p_x d_x p_y d_y

p = [100., 1.0, 50., 1.0]
u0 = [0, 0]
tspan = (0., 10)
prob = ODEProblem(model, float.(u0), tspan, p)
odesol = solve(prob)

discrete_prob = DiscreteProblem(u0,tspan,p)
jump_prob = JumpProblem(discrete_prob,Direct(),model)
sol = solve(jump_prob,FunctionMap())


plot(odesol)
plot!(sol)
```

Here, the `y` variable remains at 0 with the Jump equations (which it should not do and which it did not use to do). 

I could try to pinpoint where the issue was introduced, but I figured that @isaacsas or @ChrisRackauckas  may already know what has gone wrong.

**Comment by korsbo** [comment]
Also, the average value of `x` for the jump equation is off in this example. And if you stop using the hill function, the `x` value will be right again.

**Comment by korsbo** [comment]
Pinning DiffEqBiological to v3.4.2 solves the issue, the problem is here.

**Comment by isaacsas** [comment]
3.5 was a big change, so it certainly could have introduced a bug. I'll look at your example and get back to you in the next few days. (Might not be till the weekend -- this week is super busy.)

**Comment by isaacsas** [comment]
@korsbo had a light office hours, so I think I've got this fixed now on master. Let me know if you have any other problems, otherwise I'll plan to tag a new release tonight.

**Comment by ChrisRackauckas** [comment]
Looks good to me

**Comment by isaacsas** [comment]
OK, I'll tag a release now then.
