### ISSUE TITLE
Support for different input formats

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqBiological.jl#86]
While direct SBML would be great I suspect it will be a while till someone gets around to that. 

As a stop gap we might consider allowing import of simpler formats that can be generated by other tools, such as [SBML converters](http://sbml.org/Special/SBMLMatrix/static-summary.html#cat_3).

In particular, [BioNetGen](https://www.csb.pitt.edu/Faculty/Faeder/?page_id=409) is fairly popular, and has its own language, BNGL, that allows the specification of reaction networks much more compactly than SBML. BioNetGen can also, I believe, import SBML (though I'm not sure what subset of SBML features it currently handles). What's nice about this is they have a greatly simplified "network" file format that is very similar to our DSL, and which they use internally to feed into their solvers. (So I think the BioNetGen workflow is to parse the BNGL/SBML network, expand out the reactions, generate a network file, and feed this file as input into stochastic or ODE solver executables.) The network generation program that generates this reduced file can be run through the commandline. At least an older version of this format is specified in the references to the [BioNetGen bible](https://www.csb.pitt.edu/Faculty/Faeder/Publications/Reprints/Faeder_2009.pdf). 

So we could consider wrapping the BioNetGen network creation executable with a separate Julia Package (BioNetGen is MIT FWIW), to allow generation of ".net" files, and then add a parser for the ".net" file. The only real challenge I see with the latter is that I think the ".net" files now allow the specification of mathematical expressions for non-standard rate laws. Otherwise the format is quite simple, see the BCR network [here](https://gist.github.com/isaacsas/6b28cdb0bc558f190c8e98e6d46e9b1a). (Note, the generated species names are insanely long as they are coming from a more compact BNGL specification, and encode different complexes / phosphorylation states.)

So I guess the question is 
1. Does it make sense to create a package wrapping the BioNetGen network creation executable?
2. Would a ".net" file parser for importing files processed by the wrapper (or standalone BioNetGen) be of interest to anyone else?

**Comment by TorkelE** [comment]
Admittedly I have no personal experience of SBML or BioNetGen, so I cannot with much accuracy tell how useful such a feature would be to the community, nor what amount of effort it would be to implement.

However, I think it sounds like a nice thing to have. With DifEqBiological now split from the main DifferentialEquations import we should have a bit more freedom to "bloat" the package with more features that aren't as directly related to the DiffEq solvers as before. It would then make sense to gather up various tools useful for reaction networks.

(Basically, this should good, but I am not sure whenever I can be of much help, at least not right now)

**Comment by isaacsas** [comment]
I emailed the BioNetGen authors to see if they have a spec for the .net file format anywhere. If it doesn't look too bad I may take a crack at parsing it.

**Comment by isaacsas** [comment]
Just an update; the BioNetGen authors say the .net files are being treated as an internal communication protocol between the BioNetGen components, and because of that the format is not really documented anywhere (an earlier version was documented in their 2009 book chapter, but new features have been added). They suggested several alternatives, i.e. having BioNetGen output XML, or writing a plugin to BioNetGen that can output in our format. What is nice about the .net format is that it is relatively straightforward and compact, and, unlike XML/SBML, human readable. 

I may go ahead and parse the .net files anyways, with the understanding that it could break at any time if they update BioNetGen. The parser may not support all their features, so the importer might be fragile, but at least it should allow for standard networks to be imported.

**Comment by isaacsas** [comment]
As [ReactionNetworkImporters](https://github.com/isaacsas/ReactionNetworkImporters.jl) has been released and has support for basic BioNetGen .net files and the RSSA filetype I'll close this.
