### ISSUE TITLE
Generated ODE expressions have extra (zero) terms

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqBiological.jl#89]
Coding the repressilator:
```
repressilator = @reaction_network begin
    hillr(P₃,α,K,n), ∅ --> m₁
    (δ,γ), m₁ ↔ ∅
    hillr(P₁,α,K,n), ∅ --> m₂
    (δ,γ), m₂ ↔ ∅
    hillr(P₂,α,K,n), ∅ --> m₃
    (δ,γ), m₃ ↔ ∅
    β, m₁ --> m₁ + P₁
    μ, P₁ --> ∅
    β, m₂ --> m₂ + P₂
    μ, P₂ --> ∅
    β, m₃ --> m₃ + P₃
    μ, P₃ --> ∅
end α K n δ γ β μ
```
gives:
```
julia> repressilator.f_func
6-element Array{Expr,1}:
 :((α * K ^ n) / (K ^ n + P₃ ^ n) + -1 * δ * m₁ + γ + 0)
 :((α * K ^ n) / (K ^ n + P₁ ^ n) + -1 * δ * m₂ + γ + 0)
 :((α * K ^ n) / (K ^ n + P₂ ^ n) + -1 * δ * m₃ + γ + 0)
 :(β * m₁ + -1 * μ * P₁)                                
 :(β * m₂ + -1 * μ * P₂)                                
 :(β * m₃ + -1 * μ * P₃)     
```

While I assume the extra `+0` gets optimized away when the actual ODE function is compiled, it would be nice to get it out of the expression since it appears in other contexts (such as displaying the ODEs with Latexify).

**Comment by isaacsas** [comment]
The issue here seems to be the "m --> m + P" reactions, which result in the zeroes within the "m" ODEs. One can get rid of this by using "k*m, 0 --> P", but then the reaction is not classified as mass action, which has performance implications in the jump setting.

**Comment by TorkelE** [comment]
I can have a look at this next week. A lot of expressions looking a bit weird is generated by the parsing, there is a clean function which serves no real purpose but removes this excessive weirdness. That could probably be expanded to fix this as well.

**Comment by isaacsas** [comment]
That’d be great, thanks! Getting rid of expressions that multiply by zero or add zero would be awesome. (There’s also stuff like “+ -1 * mu”, which would be nice to simplify, but isn’t as annoying.)

**Comment by TorkelE** [comment]
Getting rid of + -1 * stuff is harder, due to a limitation of how expressions are constructed. What one can do is to after the expression have been generated, gather up all the positive parts and negative parts and the write something like ...+...+...-(...+...+...). ('-' can only exist as a x-y, or as a part of a number. However, this case should be fixed in Latexify so it will not appear there at least.

**Comment by isaacsas** [comment]
I had feeling that would be harder to handle. It would be great if at least Latexify can compensate for it.

**Comment by ChrisRackauckas** [comment]
Can the typing in Latexify be expanded to `Union{Symbol,Expr,Number}`?

**Comment by isaacsas** [comment]
Actually, [Latexify](https://github.com/korsbo/Latexify.jl) does seem to properly deal with the "-1" coefficients:
<img width="246" alt="repressilator" src="https://user-images.githubusercontent.com/9385167/52535778-71070680-2d20-11e9-9dfb-d613a0bd127a.png">

**Comment by korsbo** [comment]
Latexify has a hacky function to clean up the "-1" coeffs, found [here](https://github.com/korsbo/Latexify.jl/blob/efcb55eca0d396e64bc7a4dda73222fb495ebd83/src/plugins/DiffEqBiological.jl#L122). Feel free to copy the function into DiffEqBiological if you'd rather have this cleaning done at the source.

**Comment by isaacsas** [comment]
Per discussion yesterday with @ChrisRackauckas it appears the `+0` terms actually don't always get optimized away by the compiler in the ODE functions. We should fix this at some point.

**Comment by isaacsas** [comment]
It looks like the `-1*A` type terms are also not getting simplified to subtractions. We should perhaps also use the `Latexify` `-1` cleaning function on the expressions before generating the final ODE rhs.

**Comment by isaacsas** [comment]
Closed by [103](https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/103).
